name: jsonml
version: 0.1.0
description: JsonML for Dart
author: Filip Hracek <filip.hracek@gmail.com>
dependencies:
  html5lib: 0.9.1
  browser: 0.9.1
dev_dependencies:
  unittest: any
  benchmark_harness: any