name: jsonml
version: 0.1.0
description: JsonML in Dart
author: Filip Hracek <filip.hracek@gmail.com>
dependencies:
  html5lib: ">=0.10.0 <0.11.0"
  browser: ">=0.10.0+2 <0.11.0"
dev_dependencies:
  unittest: any
  benchmark_harness: any