name: jsonml
description: >
  Library for converting to and from JsonML. Can display JsonML in the DOM
  and can convert JsonML to and from HTML representations.
homepage: https://github.com/filiph/jsonml
version: 0.1.9

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  html: "0.14.0+3 <0.15.0"

dev_dependencies:
  benchmark_harness: ^1.0.4
  build_runner: ^1.10.1
  build_web_compilers: ^2.11.0
  test: ^1.15.3
