name: jsonml
description: >
  Library for converting to and from JsonML. Can display JsonML in the DOM
  and can convert JsonML to and from HTML representations.
homepage: https://github.com/filiph/jsonml
version: 0.2.1

environment:
  sdk: '>=2.12.0 <3.1.5'

dependencies:
  html: ">=0.15.0 <0.15.4"

dev_dependencies:
  benchmark_harness: ^2.2.1
  build_runner: ^2.3.0
  build_web_compilers: ^3.2.6
  pedantic: ^1.9.0
  test: ^1.15.3
