name: jsonml
description: Library for converting to and from JsonML.
homepage: https://github.com/filiph/jsonml
version: 0.1.7
author: Filip Hracek <filip.hracek@gmail.com>
dependencies:
  html5lib: ">=0.12.0 <0.13.0"
  browser: ">=0.10.0+2 <0.11.0"
dev_dependencies:
  unittest: any
  benchmark_harness: any