name: jsonml
description: >
  Library for converting to and from JsonML. Can display JsonML in the DOM
  and can convert JsonML to and from HTML representations.
homepage: https://github.com/filiph/jsonml
version: 0.1.8+1
author: Filip Hracek <filip.hracek@gmail.com>

environment:
  sdk: '>=2.0.0-dev.69.0 <3.0.0'

dependencies:
  html: ">=0.13.3+2 <0.14.0"
dev_dependencies:
  benchmark_harness: ^1.0.4
  build_runner: '>=0.8.10 <0.10.0'
  build_web_compilers: '>=0.3.6 <0.5.0'
  test: ^1.3.0
